# Site settings
title: PRML

email: "dapone21@gmail.com"
url: "http://prmlstd.github.io"
github_url: "http://github.com/prmlstd/prml"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/prmlstd"
baseurl: "/prml"
disqus_shortname: prmlstdgithub

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
